// Catalogo Servizi Ufficiali, Prezzi IT/RO, Link Diretti di Disdetta e Guida "Come Disdire" (Italia 🇮🇹 + Romania 🇷🇴)
window.SERVICE_PRESETS = [
  // --- STREAMING & INTRATTENIMENTO ---
  {
    id: 'netflix',
    name: 'Netflix',
    name_ro: 'Netflix',
    brandTag: 'N',
    country: 'all',
    category: 'streaming',
    itemType: 'subscription',
    defaultPrice: 13.99,
    defaultPriceRON: 49.99,
    defaultCurrency: 'EUR',
    billingCycle: 'monthly',
    remindDaysBefore: 3,
    color: '#E50914',
    icon: '🎬',
    cancelUrl: 'https://www.netflix.com/youraccount',
    directCancelUrl: 'https://www.netflix.com/CancelPlan',
    howToCancel_it: 'Apri netflix.com/CancelPlan → Clicca sul pulsante "Completa la disdetta" (1 click).',
    howToCancel_ro: 'Deschide netflix.com/CancelPlan → Apasă pe butonul "Finalizează anularea" (1 click).',
    notesPlaceholder: 'Piano Standard / Premium',
    plans: [
      { label: 'Standard con pubblicità (6,99 €)', label_ro: 'Standard cu reclame (6,99 €)', price: 6.99, currency: 'EUR', cycle: 'monthly' },
      { label: 'Standard Full HD (13,99 €)', label_ro: 'Standard Full HD (13,99 €)', price: 13.99, currency: 'EUR', cycle: 'monthly' },
      { label: 'Premium 4K UHD (19,99 €)', label_ro: 'Premium 4K UHD (19,99 €)', price: 19.99, currency: 'EUR', cycle: 'monthly' },
      { label: 'RO Minim (24,99 lei)', label_ro: 'Minim RO (24,99 lei/lună)', price: 24.99, currency: 'RON', cycle: 'monthly' },
      { label: 'RO Standard (49,99 lei)', label_ro: 'Standard Full HD RO (49,99 lei/lună)', price: 49.99, currency: 'RON', cycle: 'monthly' },
      { label: 'RO Premium 4K (64,99 lei)', label_ro: 'Premium 4K RO (64,99 lei/lună)', price: 64.99, currency: 'RON', cycle: 'monthly' }
    ]
  },
  {
    id: 'disneyplus',
    name: 'Disney+',
    name_ro: 'Disney+',
    brandTag: 'D+',
    country: 'all',
    category: 'streaming',
    itemType: 'subscription',
    defaultPrice: 9.99,
    defaultPriceRON: 36.99,
    defaultCurrency: 'EUR',
    billingCycle: 'monthly',
    remindDaysBefore: 3,
    color: '#0063E5',
    icon: '✨',
    cancelUrl: 'https://www.disneyplus.com/account/subscription',
    directCancelUrl: 'https://www.disneyplus.com/account/cancel-subscription',
    howToCancel_it: 'Vai su disneyplus.com/account → Tocca il tuo Abbonamento → Clicca "Disdici abbonamento".',
    howToCancel_ro: 'Intră pe disneyplus.com/account → Apasă pe Abonamentul tău → Apasă "Anulează abonamentul".',
    notesPlaceholder: 'Standard / Premium',
    plans: [
      { label: 'Standard con pubblicità (5,99 €)', label_ro: 'Standard cu reclame (5,99 €)', price: 5.99, currency: 'EUR', cycle: 'monthly' },
      { label: 'Standard Full HD (9,99 €)', label_ro: 'Standard Full HD (9,99 €)', price: 9.99, currency: 'EUR', cycle: 'monthly' },
      { label: 'Premium 4K (13,99 €)', label_ro: 'Premium 4K (13,99 €)', price: 13.99, currency: 'EUR', cycle: 'monthly' },
      { label: 'RO Standard (36,99 lei)', label_ro: 'Standard RO (36,99 lei/lună)', price: 36.99, currency: 'RON', cycle: 'monthly' },
      { label: 'RO Premium 4K (49,99 lei)', label_ro: 'Premium 4K RO (49,99 lei/lună)', price: 49.99, currency: 'RON', cycle: 'monthly' }
    ]
  },
  {
    id: 'spotify',
    name: 'Spotify Premium',
    name_ro: 'Spotify Premium',
    brandTag: 'SP',
    country: 'all',
    category: 'streaming',
    itemType: 'subscription',
    defaultPrice: 10.99,
    defaultPriceRON: 24.00,
    defaultCurrency: 'EUR',
    billingCycle: 'monthly',
    remindDaysBefore: 3,
    color: '#1DB954',
    icon: '🎧',
    cancelUrl: 'https://www.spotify.com/account/subscription/',
    directCancelUrl: 'https://www.spotify.com/account/cancel/',
    howToCancel_it: 'Apri spotify.com/account/subscription → Clicca su "Annulla abbonamento" sotto il tuo piano.',
    howToCancel_ro: 'Deschide spotify.com/account/subscription → Apasă pe "Anulează abonamentul" sub planul tău.',
    notesPlaceholder: 'Individual / Duo / Family',
    plans: [
      { label: 'Individual (10,99 €)', label_ro: 'Individual EUR (10,99 €)', price: 10.99, currency: 'EUR', cycle: 'monthly' },
      { label: 'Duo 2 Account (14,99 €)', label_ro: 'Duo 2 Conturi EUR (14,99 €)', price: 14.99, currency: 'EUR', cycle: 'monthly' },
      { label: 'Family 6 Account (17,99 €)', label_ro: 'Family 6 Conturi EUR (17,99 €)', price: 17.99, currency: 'EUR', cycle: 'monthly' },
      { label: 'RO Individual (24,00 lei)', label_ro: 'Individual RO (24,00 lei/lună)', price: 24.00, currency: 'RON', cycle: 'monthly' },
      { label: 'RO Duo (31,00 lei)', label_ro: 'Duo RO (31,00 lei/lună)', price: 31.00, currency: 'RON', cycle: 'monthly' },
      { label: 'RO Family (38,00 lei)', label_ro: 'Family RO (38,00 lei/lună)', price: 38.00, currency: 'RON', cycle: 'monthly' }
    ]
  },
  {
    id: 'amazon-prime',
    name: 'Amazon Prime',
    name_ro: 'Amazon Prime Video',
    brandTag: 'PR',
    country: 'all',
    category: 'streaming',
    itemType: 'subscription',
    defaultPrice: 4.99,
    defaultPriceRON: 13.99,
    defaultCurrency: 'EUR',
    billingCycle: 'monthly',
    remindDaysBefore: 5,
    color: '#00A8E1',
    icon: '📦',
    cancelUrl: 'https://www.amazon.it/mc',
    directCancelUrl: 'https://www.primevideo.com/settings/your-account',
    howToCancel_it: 'Su Amazon vai su "Il mio Amazon Prime" → "Gestisci iscrizione" → "Termina iscrizione".',
    howToCancel_ro: 'Intră pe primevideo.com/settings/your-account → Apasă pe "Încheie abonamentul".',
    notesPlaceholder: 'Prime Video + Spedizioni',
    plans: [
      { label: 'Prime Mensile IT (4,99 €/mese)', label_ro: 'Prime Lunar IT (4,99 €/lună)', price: 4.99, currency: 'EUR', cycle: 'monthly' },
      { label: 'Prime Annuale IT (49,90 €/anno)', label_ro: 'Prime Anual IT (49,90 €/an)', price: 49.90, currency: 'EUR', cycle: 'yearly' },
      { label: 'Prime Video RO (13,99 lei/lună)', label_ro: 'Prime Video RO (13,99 lei/lună)', price: 13.99, currency: 'RON', cycle: 'monthly' }
    ]
  },
  {
    id: 'youtube-premium',
    name: 'YouTube Premium',
    name_ro: 'YouTube Premium',
    brandTag: 'YT',
    country: 'all',
    category: 'streaming',
    itemType: 'subscription',
    defaultPrice: 11.99,
    defaultPriceRON: 29.00,
    defaultCurrency: 'EUR',
    billingCycle: 'monthly',
    remindDaysBefore: 3,
    color: '#FF0000',
    icon: '▶️',
    cancelUrl: 'https://www.youtube.com/paid_memberships',
    directCancelUrl: 'https://www.youtube.com/paid_memberships',
    howToCancel_it: 'Apri youtube.com/paid_memberships → Clicca "Gestisci abbonamento" → "Disattiva".',
    howToCancel_ro: 'Deschide youtube.com/paid_memberships → Apasă "Gestionează abonamentul" → "Dezactivează".',
    notesPlaceholder: 'YouTube senza pubblicità + Music',
    plans: [
      { label: 'Individuale IT (11,99 €)', label_ro: 'Individual EUR (11,99 €)', price: 11.99, currency: 'EUR', cycle: 'monthly' },
      { label: 'Famiglia IT (17,99 €)', label_ro: 'Familie EUR (17,99 €)', price: 17.99, currency: 'EUR', cycle: 'monthly' },
      { label: 'Individual RO (29,00 lei)', label_ro: 'Individual RO (29,00 lei/lună)', price: 29.00, currency: 'RON', cycle: 'monthly' },
      { label: 'Familie RO (55,00 lei)', label_ro: 'Familie RO (55,00 lei/lună)', price: 55.00, currency: 'RON', cycle: 'monthly' }
    ]
  },
  {
    id: 'dazn',
    name: 'DAZN',
    name_ro: 'DAZN',
    brandTag: 'DZ',
    country: 'all',
    category: 'streaming',
    itemType: 'subscription',
    defaultPrice: 34.99,
    defaultPriceRON: 99.00,
    defaultCurrency: 'EUR',
    billingCycle: 'monthly',
    remindDaysBefore: 7,
    color: '#18181B',
    icon: '⚽',
    cancelUrl: 'https://www.dazn.com/it-IT/myaccount',
    directCancelUrl: 'https://www.dazn.com/it-IT/myaccount/subscription',
    howToCancel_it: 'Vai su dazn.com/myaccount → "Abbonamento" → "Non voglio rinnovare" (attenzione ai 30gg di preavviso!).',
    howToCancel_ro: 'Intră pe dazn.com/myaccount → "Abonament" → "Anulează abonamentul".',
    notesPlaceholder: 'Attenzione al preavviso di disdetta!',
    plans: [
      { label: 'DAZN Start (14,99 €)', label_ro: 'DAZN Start (14,99 €)', price: 14.99, currency: 'EUR', cycle: 'monthly' },
      { label: 'DAZN Standard (34,99 €)', label_ro: 'DAZN Standard (34,99 €)', price: 34.99, currency: 'EUR', cycle: 'monthly' },
      { label: 'DAZN Plus (59,99 €)', label_ro: 'DAZN Plus (59,99 €)', price: 59.99, currency: 'EUR', cycle: 'monthly' }
    ]
  },
  {
    id: 'max-hbo',
    name: 'Max (HBO)',
    name_ro: 'Max (HBO)',
    brandTag: 'MX',
    country: 'all',
    category: 'streaming',
    itemType: 'subscription',
    defaultPrice: 9.99,
    defaultPriceRON: 34.90,
    defaultCurrency: 'RON',
    billingCycle: 'monthly',
    remindDaysBefore: 3,
    color: '#002BE7',
    icon: '🎥',
    cancelUrl: 'https://auth.max.com/',
    directCancelUrl: 'https://www.max.com/account',
    howToCancel_it: 'Apri max.com/account → Sezione Abbonamento → Clicca "Annulla abbonamento".',
    howToCancel_ro: 'Intră pe max.com/account → Secțiunea Abonament → Apasă "Anulează abonamentul".',
    notesPlaceholder: 'Max Streaming',
    plans: [
      { label: 'Max Standard RO (34,90 lei)', label_ro: 'Max Standard RO (34,90 lei/lună)', price: 34.90, currency: 'RON', cycle: 'monthly' },
      { label: 'Max Ultimate 4K RO (49,90 lei)', label_ro: 'Max Ultimate 4K RO (49,90 lei/lună)', price: 49.90, currency: 'RON', cycle: 'monthly' },
      { label: 'Max Standard EUR (9,99 €)', label_ro: 'Max Standard EUR (9,99 €/lună)', price: 9.99, currency: 'EUR', cycle: 'monthly' }
    ]
  },
  {
    id: 'voyo-ro',
    name: 'VOYO.ro 🇷🇴',
    name_ro: 'VOYO 🇷🇴',
    brandTag: 'VY',
    country: 'ro',
    category: 'streaming',
    itemType: 'subscription',
    defaultPrice: 4.76,
    defaultPriceRON: 24.00,
    defaultCurrency: 'RON',
    billingCycle: 'monthly',
    remindDaysBefore: 3,
    color: '#E11D48',
    icon: '📺',
    cancelUrl: 'https://voyo.protv.ro/profilul-meu',
    directCancelUrl: 'https://voyo.protv.ro/profilul-meu',
    howToCancel_it: 'Apri voyo.protv.ro/profilul-meu → "Abonamentul meu" → "Anulează abonamentul".',
    howToCancel_ro: 'Deschide voyo.protv.ro/profilul-meu → "Abonamentul meu" → Apasă "Anulează abonamentul".',
    notesPlaceholder: 'Abonament VOYO Romania',
    plans: [
      { label: 'Abonament Lunar (~24 lei)', label_ro: 'Abonament Lunar (~24,00 lei)', price: 24.00, currency: 'RON', cycle: 'monthly' },
      { label: 'Abonament Lunar (4,76 €)', label_ro: 'Abonament Lunar (4,76 €)', price: 4.76, currency: 'EUR', cycle: 'monthly' }
    ]
  },
  {
    id: 'nowtv',
    name: 'NOW TV 🇮🇹',
    name_ro: 'NOW TV 🇮🇹',
    brandTag: 'NW',
    country: 'it',
    category: 'streaming',
    itemType: 'subscription',
    defaultPrice: 14.99,
    defaultPriceRON: 74.00,
    defaultCurrency: 'EUR',
    billingCycle: 'monthly',
    remindDaysBefore: 3,
    color: '#00D66C',
    icon: '📺',
    cancelUrl: 'https://www.nowtv.it/area-personale',
    directCancelUrl: 'https://www.nowtv.it/area-personale',
    howToCancel_it: 'Vai su nowtv.it/area-personale → "La mia offerta" → Clicca "Disattiva rinnovo" almeno 24h prima.',
    howToCancel_ro: 'Intră pe nowtv.it/area-personale → "La mia offerta" → "Disattiva rinnovo".',
    notesPlaceholder: 'Pass Cinema / Entertainment / Sport'
  },
  {
    id: 'apple-tv',
    name: 'Apple TV+',
    name_ro: 'Apple TV+',
    brandTag: 'TV+',
    country: 'all',
    category: 'streaming',
    itemType: 'subscription',
    defaultPrice: 9.99,
    defaultPriceRON: 49.99,
    defaultCurrency: 'EUR',
    billingCycle: 'monthly',
    remindDaysBefore: 3,
    color: '#334155',
    icon: '🍎',
    cancelUrl: 'https://tv.apple.com/settings',
    directCancelUrl: 'https://support.apple.com/HT202039',
    howToCancel_it: 'Impostazioni iPhone → Tocca il tuo nome → "Abbonamenti" → Apple TV+ → "Annulla abbonamento".',
    howToCancel_ro: 'Configurări iPhone → Apasă pe numele tău → "Abonamente" → Apple TV+ → "Anulați abonamentul".',
    notesPlaceholder: 'ID Apple'
  },

  // --- GAMING, SOFTWARE & AI ---
  {
    id: 'chatgpt',
    name: 'ChatGPT Plus',
    name_ro: 'ChatGPT Plus',
    brandTag: 'AI',
    country: 'all',
    category: 'software',
    itemType: 'subscription',
    defaultPrice: 22.00,
    defaultPriceRON: 110.00,
    defaultCurrency: 'EUR',
    billingCycle: 'monthly',
    remindDaysBefore: 3,
    color: '#10A37F',
    icon: '🤖',
    cancelUrl: 'https://chatgpt.com/#settings/Subscription',
    directCancelUrl: 'https://chatgpt.com/#settings/Subscription',
    howToCancel_it: 'Apri chatgpt.com → Impostazioni → Abbonamento → "Gestisci" → "Annulla piano".',
    howToCancel_ro: 'Deschide chatgpt.com → Setări → Abonament → "Gestionează" → "Anulează abonamentul".',
    notesPlaceholder: 'OpenAI Plus'
  },
  {
    id: 'ps-plus',
    name: 'PlayStation Plus',
    name_ro: 'PlayStation Plus',
    brandTag: 'PS+',
    country: 'all',
    category: 'software',
    itemType: 'subscription',
    defaultPrice: 8.99,
    defaultPriceRON: 45.00,
    defaultCurrency: 'EUR',
    billingCycle: 'monthly',
    remindDaysBefore: 3,
    color: '#00439C',
    icon: '🕹️',
    cancelUrl: 'https://store.playstation.com/',
    directCancelUrl: 'https://www.playstation.com/acct/management',
    howToCancel_it: 'Su PS5/Web vai su Gestione Account → "Abbonamenti" → PS Plus → "Annulla abbonamento".',
    howToCancel_ro: 'Intră în Gestionare Cont PlayStation → "Abonamente" → PS Plus → "Anulează abonamentul".',
    notesPlaceholder: 'Essential / Extra / Premium',
    plans: [
      { label: 'Essential 1 Mese (8,99 €)', label_ro: 'Essential 1 Lună (45 lei / 8,99 €)', price: 8.99, currency: 'EUR', cycle: 'monthly' },
      { label: 'Extra 1 Mese (13,99 €)', label_ro: 'Extra 1 Lună (70 lei / 13,99 €)', price: 13.99, currency: 'EUR', cycle: 'monthly' },
      { label: 'Premium 1 Mese (16,99 €)', label_ro: 'Premium 1 Lună (85 lei / 16,99 €)', price: 16.99, currency: 'EUR', cycle: 'monthly' }
    ]
  },
  {
    id: 'xbox-gamepass',
    name: 'Xbox Game Pass',
    name_ro: 'Xbox Game Pass',
    brandTag: 'XB',
    country: 'all',
    category: 'software',
    itemType: 'subscription',
    defaultPrice: 14.99,
    defaultPriceRON: 74.00,
    defaultCurrency: 'EUR',
    billingCycle: 'monthly',
    remindDaysBefore: 3,
    color: '#107C10',
    icon: '🎮',
    cancelUrl: 'https://account.microsoft.com/services',
    directCancelUrl: 'https://account.microsoft.com/services',
    howToCancel_it: 'Vai su account.microsoft.com/services → Clicca "Gestisci" su Game Pass → "Annulla abbonamento".',
    howToCancel_ro: 'Intră pe account.microsoft.com/services → Apasă "Gestionează" la Game Pass → "Anulează abonamentul".',
    notesPlaceholder: 'PC / Console / Ultimate'
  },
  {
    id: 'icloud',
    name: 'iCloud+',
    name_ro: 'iCloud+',
    brandTag: 'iC',
    country: 'all',
    category: 'software',
    itemType: 'subscription',
    defaultPrice: 2.99,
    defaultPriceRON: 14.99,
    defaultCurrency: 'EUR',
    billingCycle: 'monthly',
    remindDaysBefore: 3,
    color: '#0EA5E9',
    icon: '☁️',
    cancelUrl: 'https://support.apple.com/108047',
    directCancelUrl: 'https://support.apple.com/108047',
    howToCancel_it: 'Impostazioni iPhone → ID Apple → iCloud → "Gestisci spazio" → "Cambia piano" → Opzioni di downgrade.',
    howToCancel_ro: 'Configurări iPhone → ID Apple → iCloud → "Gestionați spațiul" → "Schimbați planul".',
    notesPlaceholder: '50GB / 200GB / 2TB',
    plans: [
      { label: '50 GB (0,99 €)', label_ro: '50 GB (4,99 lei / 0,99 €)', price: 0.99, currency: 'EUR', cycle: 'monthly' },
      { label: '200 GB (2,99 €)', label_ro: '200 GB (14,99 lei / 2,99 €)', price: 2.99, currency: 'EUR', cycle: 'monthly' },
      { label: '2 TB (9,99 €)', label_ro: '2 TB (49,99 lei / 9,99 €)', price: 9.99, currency: 'EUR', cycle: 'monthly' }
    ]
  },
  {
    id: 'google-one',
    name: 'Google Play / Google One',
    name_ro: 'Google Play / Google One',
    brandTag: 'G1',
    country: 'all',
    category: 'software',
    itemType: 'subscription',
    defaultPrice: 1.99,
    defaultPriceRON: 9.99,
    defaultCurrency: 'EUR',
    billingCycle: 'monthly',
    remindDaysBefore: 3,
    color: '#4285F4',
    icon: '🌈',
    cancelUrl: 'https://play.google.com/store/account/subscriptions',
    directCancelUrl: 'https://play.google.com/store/account/subscriptions',
    howToCancel_it: 'Apri play.google.com/store/account/subscriptions → Seleziona l\'abbonamento → "Annulla abbonamento".',
    howToCancel_ro: 'Deschide play.google.com/store/account/subscriptions → Selectează abonamentul → "Anulează abonamentul".',
    notesPlaceholder: '100GB / 2TB / App Google Play'
  },

  // --- BOLLETTE & UTENZE ITALIA 🇮🇹 ---
  {
    id: 'bolletta-luce',
    name: 'Bolletta Luce 🇮🇹',
    name_ro: 'Bolletta Luce 🇮🇹',
    brandTag: 'LUCE',
    country: 'it',
    category: 'bills',
    itemType: 'bill',
    defaultPrice: 85.00,
    defaultPriceRON: 420.00,
    defaultCurrency: 'EUR',
    billingCycle: 'bimonthly',
    remindDaysBefore: 7,
    color: '#F59E0B',
    icon: '⚡',
    cancelUrl: 'https://www.enel.it/it/area-clienti',
    directCancelUrl: '',
    howToCancel_it: 'Bolletta periodica: paga tramite PagoPA, domiciliazione o Area Clienti prima della scadenza.',
    howToCancel_ro: 'Factură energie Italia.',
    notesPlaceholder: 'Enel, Plenitude, A2A, Edison, Sorgenia...'
  },
  {
    id: 'bolletta-gas',
    name: 'Bolletta Gas 🇮🇹',
    name_ro: 'Bolletta Gas 🇮🇹',
    brandTag: 'GAS',
    country: 'it',
    category: 'bills',
    itemType: 'bill',
    defaultPrice: 95.00,
    defaultPriceRON: 470.00,
    defaultCurrency: 'EUR',
    billingCycle: 'bimonthly',
    remindDaysBefore: 7,
    color: '#EF4444',
    icon: '🔥',
    cancelUrl: 'https://eniplenitude.com/my-eni',
    directCancelUrl: '',
    howToCancel_it: 'Ricorda di comunicare l\'autolettura del contatore e pagare entro la data di scadenza.',
    howToCancel_ro: 'Factură gaz Italia.',
    notesPlaceholder: 'Fornitore Gas / Lettura contatore'
  },
  {
    id: 'fibra-casa',
    name: 'Internet Fibra Casa 🇮🇹',
    name_ro: 'Internet Fibra 🇮🇹',
    brandTag: 'WIFI',
    country: 'it',
    category: 'bills',
    itemType: 'bill',
    defaultPrice: 27.90,
    defaultPriceRON: 139.00,
    defaultCurrency: 'EUR',
    billingCycle: 'monthly',
    remindDaysBefore: 5,
    color: '#6366F1',
    icon: '🌐',
    cancelUrl: '',
    directCancelUrl: '',
    howToCancel_it: 'Controlla l\'addebito mensile nell\'Area Clienti TIM / Iliad / Vodafone / Fastweb / WindTre.',
    howToCancel_ro: 'Abonament internet Italia.',
    notesPlaceholder: 'TIM / Vodafone / Fastweb / Iliad / WindTre'
  },
  {
    id: 'tari',
    name: 'TARI (Tassa Rifiuti) 🇮🇹',
    name_ro: 'TARI 🇮🇹',
    brandTag: 'TARI',
    country: 'it',
    category: 'bills',
    itemType: 'bill',
    defaultPrice: 180.00,
    defaultPriceRON: 890.00,
    defaultCurrency: 'EUR',
    billingCycle: 'yearly',
    remindDaysBefore: 14,
    color: '#10B981',
    icon: '♻️',
    cancelUrl: '',
    directCancelUrl: '',
    howToCancel_it: 'Paga tramite F24 o avviso PagoPA ricevuto dal tuo Comune.',
    howToCancel_ro: 'Taxă salubritate Italia.',
    notesPlaceholder: 'Rata TARI Comunale / PagoPA'
  },

  // --- FACTURI & UTILITĂȚI ROMANIA 🇷🇴 ---
  {
    id: 'digi-ro',
    name: 'DIGI (RCS & RDS) 🇷🇴',
    name_ro: 'DIGI (Internet, TV & Mobil) 🇷🇴',
    brandTag: 'DIGI',
    country: 'ro',
    category: 'bills',
    itemType: 'bill',
    defaultPrice: 19.00,
    defaultPriceRON: 95.00,
    defaultCurrency: 'RON',
    billingCycle: 'monthly',
    remindDaysBefore: 5,
    color: '#0284C7',
    icon: '🌐',
    cancelUrl: 'https://www.digi.ro/my-account',
    directCancelUrl: 'https://www.digi.ro/my-account/facturi',
    howToCancel_it: 'Accedi a digi.ro/my-account per pagare la fattura mensile.',
    howToCancel_ro: 'Intră în Contul Meu DIGI (digi.ro/my-account) → "Facturile mele" pentru plată online.',
    notesPlaceholder: 'Internet Fibra + TV + Mobil (Contul Meu DIGI)'
  },
  {
    id: 'curent-ro',
    name: 'Curent Electric (PPC / Hidroelectrica) 🇷🇴',
    name_ro: 'Curent Electric (Hidroelectrica / PPC) 🇷🇴',
    brandTag: 'PPC',
    country: 'ro',
    category: 'bills',
    itemType: 'bill',
    defaultPrice: 36.00,
    defaultPriceRON: 180.00,
    defaultCurrency: 'RON',
    billingCycle: 'monthly',
    remindDaysBefore: 7,
    color: '#F59E0B',
    icon: '⚡',
    cancelUrl: 'https://client.hidroelectrica.ro/',
    directCancelUrl: 'https://www.myppc.ro/',
    howToCancel_it: 'Fattura energia elettrica Romania.',
    howToCancel_ro: 'Nu uita să transmiți indexul autocitit și să achiți factura până la scadență (iHidro / myPPC).',
    notesPlaceholder: 'Factură energie electrică + transmitere index'
  },
  {
    id: 'gaze-ro',
    name: 'Gaze Naturale (Engie / E.ON) 🇷🇴',
    name_ro: 'Gaze Naturale (Engie / E.ON) 🇷🇴',
    brandTag: 'GAZ',
    country: 'ro',
    category: 'bills',
    itemType: 'bill',
    defaultPrice: 44.00,
    defaultPriceRON: 220.00,
    defaultCurrency: 'RON',
    billingCycle: 'monthly',
    remindDaysBefore: 7,
    color: '#EF4444',
    icon: '🔥',
    cancelUrl: 'https://my.engie.ro/',
    directCancelUrl: 'https://myline-eon.ro/',
    howToCancel_it: 'Fattura gas Romania.',
    howToCancel_ro: 'Verifică factura și perioada de transmitere index în contul MyENGIE sau E.ON Myline.',
    notesPlaceholder: 'Factură gaze + autocitire index'
  },
  {
    id: 'intretinere-ro',
    name: 'Întreținere Bloc (e-Bloc / Pago) 🇷🇴',
    name_ro: 'Întreținere Bloc (e-Bloc / Pago) 🇷🇴',
    brandTag: 'BLOC',
    country: 'ro',
    category: 'bills',
    itemType: 'bill',
    defaultPrice: 70.00,
    defaultPriceRON: 350.00,
    defaultCurrency: 'RON',
    billingCycle: 'monthly',
    remindDaysBefore: 7,
    color: '#64748B',
    icon: '🏢',
    cancelUrl: 'https://www.e-bloc.ro/',
    directCancelUrl: 'https://www.e-bloc.ro/',
    howToCancel_it: 'Spese condominiali Romania (e-Bloc).',
    howToCancel_ro: 'Verifică afișierul și plătește întreținerea și apometrele pe e-bloc.ro sau aplicația Pago.',
    notesPlaceholder: 'Asociația de proprietari / Apă rece & caldă'
  },
  {
    id: 'mobil-ro',
    name: 'Orange / Vodafone / YOXO 🇷🇴',
    name_ro: 'Abonament Mobil (Orange / YOXO / Vodafone) 🇷🇴',
    brandTag: 'SIM',
    country: 'ro',
    category: 'bills',
    itemType: 'subscription',
    defaultPrice: 8.00,
    defaultPriceRON: 39.00,
    defaultCurrency: 'RON',
    billingCycle: 'monthly',
    remindDaysBefore: 3,
    color: '#F97316',
    icon: '📱',
    cancelUrl: 'https://www.orange.ro/myaccount/',
    directCancelUrl: 'https://www.yoxo.ro/',
    howToCancel_it: 'Abbonamento mobile Romania.',
    howToCancel_ro: 'Gestionează abonamentul din aplicația My Orange, YOXO sau My Vodafone.',
    notesPlaceholder: 'Abonament telefon mobil Romania'
  },

  // --- AUTO & VEICOLI (ITALIA 🇮🇹 + ROMANIA 🇷🇴) ---
  {
    id: 'bollo-auto',
    name: 'Bollo Auto 🇮🇹',
    name_ro: 'Bollo Auto 🇮🇹',
    brandTag: 'ACI',
    country: 'it',
    category: 'auto',
    itemType: 'bill',
    defaultPrice: 210.00,
    defaultPriceRON: 1040.00,
    defaultCurrency: 'EUR',
    billingCycle: 'yearly',
    remindDaysBefore: 15,
    color: '#DC2626',
    icon: '🚗',
    cancelUrl: 'https://www.aci.it/i-servizi/servizi-online/bollo-auto.html',
    directCancelUrl: 'https://www.aci.it/i-servizi/servizi-online/bollo-auto.html',
    howToCancel_it: 'Paga entro l\'ultimo giorno del mese successivo alla scadenza su ACI, App IO o PagoPA.',
    howToCancel_ro: 'Taxă auto anuală Italia.',
    notesPlaceholder: 'Inserisci Targa veicolo e Regione'
  },
  {
    id: 'assicurazione-auto',
    name: 'Assicurazione Auto (RCA) 🇮🇹',
    name_ro: 'Assicurazione RCA 🇮🇹',
    brandTag: 'RCA',
    country: 'it',
    category: 'auto',
    itemType: 'bill',
    defaultPrice: 480.00,
    defaultPriceRON: 2380.00,
    defaultCurrency: 'EUR',
    billingCycle: 'yearly',
    remindDaysBefore: 15,
    color: '#2563EB',
    icon: '🛡️',
    cancelUrl: 'https://www.ilportaledellautomobilista.it/',
    directCancelUrl: '',
    howToCancel_it: 'L\'RCA non ha tacito rinnovo: confronta i preventivi 15 giorni prima della scadenza!',
    howToCancel_ro: 'Asigurare RCA Italia.',
    notesPlaceholder: 'Compagnia assicurativa + Targa'
  },
  {
    id: 'rovinieta-ro',
    name: 'Rovinietă Auto (CNAIR) 🇷🇴',
    name_ro: 'Rovinietă Auto (eRovinieta) 🇷🇴',
    brandTag: 'ROV',
    country: 'ro',
    category: 'auto',
    itemType: 'bill',
    defaultPrice: 28.00,
    defaultPriceRON: 139.00,
    defaultCurrency: 'RON',
    billingCycle: 'yearly',
    remindDaysBefore: 10,
    color: '#DC2626',
    icon: '🛣️',
    cancelUrl: 'https://www.erovinieta.ro/',
    directCancelUrl: 'https://www.erovinieta.ro/',
    howToCancel_it: 'Rinnova la Rovinietă su erovinieta.ro prima di circolare fuori città.',
    howToCancel_ro: 'Verifică valabilitatea și cumpără rovinieta online pe erovinieta.ro înainte de expirare.',
    notesPlaceholder: 'Număr înmatriculare • Rovinietă 12 luni / 30 zile'
  },
  {
    id: 'rca-ro',
    name: 'Asigurare RCA Auto 🇷🇴',
    name_ro: 'Asigurare RCA Auto 🇷🇴',
    brandTag: 'RCA',
    country: 'ro',
    category: 'auto',
    itemType: 'bill',
    defaultPrice: 190.00,
    defaultPriceRON: 950.00,
    defaultCurrency: 'RON',
    billingCycle: 'yearly',
    remindDaysBefore: 15,
    color: '#2563EB',
    icon: '🛡️',
    cancelUrl: 'https://www.aida.info.ro/polite-rca',
    directCancelUrl: 'https://www.aida.info.ro/polite-rca',
    howToCancel_it: 'Polizza RCA obbligatoria Romania.',
    howToCancel_ro: 'Reînnoiește polița RCA cu cel puțin 7 zile înainte de expirare (verifică pe aida.info.ro).',
    notesPlaceholder: 'Poliță RCA obligatorie + Număr auto'
  },
  {
    id: 'impozit-auto-ro',
    name: 'Impozit Auto (Ghișeul.ro) 🇷🇴',
    name_ro: 'Impozit Auto & Locuință (Ghișeul.ro) 🇷🇴',
    brandTag: 'TAX',
    country: 'ro',
    category: 'auto',
    itemType: 'bill',
    defaultPrice: 40.00,
    defaultPriceRON: 200.00,
    defaultCurrency: 'RON',
    billingCycle: 'yearly',
    remindDaysBefore: 15,
    color: '#059669',
    icon: '🏛️',
    cancelUrl: 'https://www.ghiseul.ro/',
    directCancelUrl: 'https://www.ghiseul.ro/',
    howToCancel_it: 'Imposta auto su Ghiseul.ro.',
    howToCancel_ro: 'Plătește online pe Ghiseul.ro până la 31 Martie pentru a beneficia de reducerea de 10%.',
    notesPlaceholder: 'Impozit anual cu reducere până la 31 Martie'
  },
  {
    id: 'itp-ro',
    name: 'ITP Auto (RAR) 🇷🇴',
    name_ro: 'Inspecția Tehnică Periodică (ITP RAR) 🇷🇴',
    brandTag: 'ITP',
    country: 'ro',
    category: 'auto',
    itemType: 'bill',
    defaultPrice: 36.00,
    defaultPriceRON: 180.00,
    defaultCurrency: 'RON',
    billingCycle: 'Biennial',
    remindDaysBefore: 20,
    color: '#D97706',
    icon: '🔧',
    cancelUrl: 'https://pro.rarom.ro/istoric_vehicul/dosar_vehicul.aspx',
    directCancelUrl: 'https://www.rarom.ro/',
    howToCancel_it: 'Revisione periodica ITP RAR.',
    howToCancel_ro: 'Programează-te la o stație ITP autorizată RAR înainte de data expirării din talon!',
    notesPlaceholder: 'Expirare ITP RAR'
  },

  // --- CASA, SALUTE & ALTRO ---
  {
    id: 'palestra',
    name: 'Palestra / Fitness',
    name_ro: 'Sală Fitness / 7card / ESX',
    brandTag: 'GYM',
    country: 'all',
    category: 'other',
    itemType: 'subscription',
    defaultPrice: 45.00,
    defaultPriceRON: 190.00,
    defaultCurrency: 'EUR',
    billingCycle: 'monthly',
    remindDaysBefore: 7,
    color: '#EC4899',
    icon: '🏋️',
    cancelUrl: '',
    directCancelUrl: '',
    howToCancel_it: 'Disdici dall\'app della palestra o invia disdetta prima del rinnovo mensile.',
    howToCancel_ro: 'Anulează reînnoirea automată din aplicația sălii (7card, ESX, World Class) înainte de scadență.',
    notesPlaceholder: 'Palestra / 7card / ESX / World Class'
  },
  {
    id: 'affitto-mutuo',
    name: 'Affitto / Mutuo',
    name_ro: 'Chirie / Rată Bancă',
    brandTag: 'HOME',
    country: 'all',
    category: 'other',
    itemType: 'bill',
    defaultPrice: 600.00,
    defaultPriceRON: 2500.00,
    defaultCurrency: 'EUR',
    billingCycle: 'monthly',
    remindDaysBefore: 5,
    color: '#4F46E5',
    icon: '🏠',
    cancelUrl: '',
    directCancelUrl: '',
    howToCancel_it: 'Bonifico mensile o addebito rata mutuo.',
    howToCancel_ro: 'Transfer bancar lunar pentru chirie sau rata creditului.',
    notesPlaceholder: 'Bonifico mensile / Addebito rata'
  }
];

window.CATEGORY_META = {
  streaming: { label: 'Streaming & Media', label_ro: 'Streaming & Media', icon: '🎬', badgeColor: '#E50914' },
  software: { label: 'App, Gaming & Cloud', label_ro: 'Aplicații, Gaming & Cloud', icon: '💻', badgeColor: '#10A37F' },
  bills: { label: 'Bollette & Utenze', label_ro: 'Facturi & Utilități', icon: '⚡', badgeColor: '#F59E0B' },
  auto: { label: 'Bollo Auto & Veicoli', label_ro: 'Auto, Rovinietă & RCA', icon: '🚗', badgeColor: '#DC2626' },
  other: { label: 'Casa, Tasse & Altro', label_ro: 'Casă, Taxe & Altele', icon: '🏠', badgeColor: '#8B5CF6' }
};

window.BILLING_CYCLES = {
  monthly: { label: 'Mensile', label_ro: 'Lunar', months: 1, short: '/mese', short_ro: '/lună' },
  bimonthly: { label: 'Bimestrale (ogni 2 mesi)', label_ro: 'Bilunar (la 2 luni)', months: 2, short: '/2 mesi', short_ro: '/2 luni' },
  quarterly: { label: 'Trimestrale (ogni 3 mesi)', label_ro: 'Trimestrial (la 3 luni)', months: 3, short: '/3 mesi', short_ro: '/3 luni' },
  semiannual: { label: 'Semestrale (ogni 6 mesi)', label_ro: 'Semestrial (la 6 luni)', months: 6, short: '/6 mesi', short_ro: '/6 luni' },
  yearly: { label: 'Annuale (ogni anno)', label_ro: 'Anual (în fiecare an)', months: 12, short: '/anno', short_ro: '/an' },
  Biennial: { label: 'Biennale (ogni 2 anni)', label_ro: 'Bienal (la 2 ani)', months: 24, short: '/2 anni', short_ro: '/2 ani' },
  once: { label: 'Singola Scadenza (1 solo mese)', label_ro: 'O singură lună', months: 0, short: '1 mese', short_ro: '1 lună' }
};
