// Catalogo Servizi Ufficiali & Piani Reali per Collegamento Rapido (Italia 🇮🇹 + Romania 🇷🇴)
window.SERVICE_PRESETS = [
  // --- STREAMING & INTRATTENIMENTO ---
  {
    id: 'netflix',
    name: 'Netflix',
    brandTag: 'N',
    category: 'streaming',
    itemType: 'subscription',
    defaultPrice: 13.99,
    defaultCurrency: 'EUR',
    billingCycle: 'monthly',
    remindDaysBefore: 3,
    color: '#E50914',
    icon: '🎬',
    cancelUrl: 'https://www.netflix.com/youraccount',
    notesPlaceholder: 'Piano Standard / Premium',
    plans: [
      { label: 'Standard con pubblicità (6,99 €)', price: 6.99, currency: 'EUR', cycle: 'monthly' },
      { label: 'Standard Full HD (13,99 €)', price: 13.99, currency: 'EUR', cycle: 'monthly' },
      { label: 'Premium 4K UHD (19,99 €)', price: 19.99, currency: 'EUR', cycle: 'monthly' },
      { label: 'RO Basic / Standard (49,99 lei)', price: 49.99, currency: 'RON', cycle: 'monthly' }
    ]
  },
  {
    id: 'disneyplus',
    name: 'Disney+',
    brandTag: 'D+',
    category: 'streaming',
    itemType: 'subscription',
    defaultPrice: 9.99,
    defaultCurrency: 'EUR',
    billingCycle: 'monthly',
    remindDaysBefore: 3,
    color: '#0063E5',
    icon: '✨',
    cancelUrl: 'https://www.disneyplus.com/account/subscription',
    notesPlaceholder: 'Standard / Premium',
    plans: [
      { label: 'Standard con pubblicità (5,99 €)', price: 5.99, currency: 'EUR', cycle: 'monthly' },
      { label: 'Standard Full HD (9,99 €)', price: 9.99, currency: 'EUR', cycle: 'monthly' },
      { label: 'Premium 4K (13,99 €)', price: 13.99, currency: 'EUR', cycle: 'monthly' },
      { label: 'RO Standard (36,99 lei)', price: 36.99, currency: 'RON', cycle: 'monthly' }
    ]
  },
  {
    id: 'spotify',
    name: 'Spotify Premium',
    brandTag: 'SP',
    category: 'streaming',
    itemType: 'subscription',
    defaultPrice: 10.99,
    defaultCurrency: 'EUR',
    billingCycle: 'monthly',
    remindDaysBefore: 3,
    color: '#1DB954',
    icon: '🎧',
    cancelUrl: 'https://www.spotify.com/account/subscription/',
    notesPlaceholder: 'Individual / Duo / Family',
    plans: [
      { label: 'Individual (10,99 €)', price: 10.99, currency: 'EUR', cycle: 'monthly' },
      { label: 'Duo 2 Account (14,99 €)', price: 14.99, currency: 'EUR', cycle: 'monthly' },
      { label: 'Family 6 Account (17,99 €)', price: 17.99, currency: 'EUR', cycle: 'monthly' },
      { label: 'RO Individual (24,00 lei)', price: 24.00, currency: 'RON', cycle: 'monthly' }
    ]
  },
  {
    id: 'amazon-prime',
    name: 'Amazon Prime',
    brandTag: 'PR',
    category: 'streaming',
    itemType: 'subscription',
    defaultPrice: 4.99,
    defaultCurrency: 'EUR',
    billingCycle: 'monthly',
    remindDaysBefore: 5,
    color: '#00A8E1',
    icon: '📦',
    cancelUrl: 'https://www.amazon.it/mc',
    notesPlaceholder: 'Prime Video + Spedizioni',
    plans: [
      { label: 'Prime Mensile IT (4,99 €/mese)', price: 4.99, currency: 'EUR', cycle: 'monthly' },
      { label: 'Prime Annuale IT (49,90 €/anno)', price: 49.90, currency: 'EUR', cycle: 'yearly' },
      { label: 'Prime Video RO (13,99 lei/lună)', price: 13.99, currency: 'RON', cycle: 'monthly' }
    ]
  },
  {
    id: 'youtube-premium',
    name: 'YouTube Premium',
    brandTag: 'YT',
    category: 'streaming',
    itemType: 'subscription',
    defaultPrice: 11.99,
    defaultCurrency: 'EUR',
    billingCycle: 'monthly',
    remindDaysBefore: 3,
    color: '#FF0000',
    icon: '▶️',
    cancelUrl: 'https://www.youtube.com/paid_memberships',
    notesPlaceholder: 'YouTube senza pubblicità + Music',
    plans: [
      { label: 'Individuale IT (11,99 €)', price: 11.99, currency: 'EUR', cycle: 'monthly' },
      { label: 'Famiglia IT (17,99 €)', price: 17.99, currency: 'EUR', cycle: 'monthly' },
      { label: 'Individual RO (29,00 lei)', price: 29.00, currency: 'RON', cycle: 'monthly' }
    ]
  },
  {
    id: 'dazn',
    name: 'DAZN',
    brandTag: 'DZ',
    category: 'streaming',
    itemType: 'subscription',
    defaultPrice: 34.99,
    defaultCurrency: 'EUR',
    billingCycle: 'monthly',
    remindDaysBefore: 7,
    color: '#18181B',
    icon: '⚽',
    cancelUrl: 'https://www.dazn.com/it-IT/myaccount',
    notesPlaceholder: 'Attenzione al preavviso di disdetta!',
    plans: [
      { label: 'DAZN Start (14,99 €)', price: 14.99, currency: 'EUR', cycle: 'monthly' },
      { label: 'DAZN Standard (34,99 €)', price: 34.99, currency: 'EUR', cycle: 'monthly' },
      { label: 'DAZN Plus (59,99 €)', price: 59.99, currency: 'EUR', cycle: 'monthly' }
    ]
  },
  {
    id: 'max-hbo',
    name: 'Max (HBO)',
    brandTag: 'MX',
    category: 'streaming',
    itemType: 'subscription',
    defaultPrice: 34.90,
    defaultCurrency: 'RON',
    billingCycle: 'monthly',
    remindDaysBefore: 3,
    color: '#002BE7',
    icon: '🎥',
    cancelUrl: 'https://auth.max.com/',
    notesPlaceholder: 'Max Streaming',
    plans: [
      { label: 'Max Standard RO (34,90 lei)', price: 34.90, currency: 'RON', cycle: 'monthly' },
      { label: 'Max Standard EUR (9,99 €)', price: 9.99, currency: 'EUR', cycle: 'monthly' }
    ]
  },
  {
    id: 'voyo-ro',
    name: 'VOYO.ro 🇷🇴',
    brandTag: 'VY',
    category: 'streaming',
    itemType: 'subscription',
    defaultPrice: 4.76,
    defaultCurrency: 'EUR',
    billingCycle: 'monthly',
    remindDaysBefore: 3,
    color: '#E11D48',
    icon: '📺',
    cancelUrl: 'https://voyo.protv.ro/profilul-meu',
    notesPlaceholder: 'Abonament VOYO Romania',
    plans: [
      { label: 'Abonament Lunar (4,76 €)', price: 4.76, currency: 'EUR', cycle: 'monthly' },
      { label: 'Abonament Lunar (~24 lei)', price: 24.00, currency: 'RON', cycle: 'monthly' }
    ]
  },
  {
    id: 'nowtv',
    name: 'NOW TV 🇮🇹',
    brandTag: 'NW',
    category: 'streaming',
    itemType: 'subscription',
    defaultPrice: 14.99,
    defaultCurrency: 'EUR',
    billingCycle: 'monthly',
    remindDaysBefore: 3,
    color: '#00D66C',
    icon: '📺',
    cancelUrl: 'https://www.nowtv.it/area-personale',
    notesPlaceholder: 'Pass Cinema / Entertainment / Sport'
  },
  {
    id: 'apple-tv',
    name: 'Apple TV+',
    brandTag: 'TV+',
    category: 'streaming',
    itemType: 'subscription',
    defaultPrice: 9.99,
    defaultCurrency: 'EUR',
    billingCycle: 'monthly',
    remindDaysBefore: 3,
    color: '#334155',
    icon: '🍎',
    cancelUrl: 'https://support.apple.com/HT202039',
    notesPlaceholder: 'ID Apple'
  },

  // --- GAMING, SOFTWARE & AI ---
  {
    id: 'chatgpt',
    name: 'ChatGPT Plus',
    brandTag: 'AI',
    category: 'software',
    itemType: 'subscription',
    defaultPrice: 22.00,
    defaultCurrency: 'EUR',
    billingCycle: 'monthly',
    remindDaysBefore: 3,
    color: '#10A37F',
    icon: '🤖',
    cancelUrl: 'https://chatgpt.com/#settings/Subscription',
    notesPlaceholder: 'OpenAI Plus'
  },
  {
    id: 'ps-plus',
    name: 'PlayStation Plus',
    brandTag: 'PS+',
    category: 'software',
    itemType: 'subscription',
    defaultPrice: 8.99,
    defaultCurrency: 'EUR',
    billingCycle: 'monthly',
    remindDaysBefore: 3,
    color: '#00439C',
    icon: '🕹️',
    cancelUrl: 'https://store.playstation.com/',
    notesPlaceholder: 'Essential / Extra / Premium',
    plans: [
      { label: 'Essential 1 Mese (8,99 €)', price: 8.99, currency: 'EUR', cycle: 'monthly' },
      { label: 'Extra 1 Mese (13,99 €)', price: 13.99, currency: 'EUR', cycle: 'monthly' },
      { label: 'Premium 1 Mese (16,99 €)', price: 16.99, currency: 'EUR', cycle: 'monthly' }
    ]
  },
  {
    id: 'xbox-gamepass',
    name: 'Xbox Game Pass',
    brandTag: 'XB',
    category: 'software',
    itemType: 'subscription',
    defaultPrice: 14.99,
    defaultCurrency: 'EUR',
    billingCycle: 'monthly',
    remindDaysBefore: 3,
    color: '#107C10',
    icon: '🎮',
    cancelUrl: 'https://account.microsoft.com/services',
    notesPlaceholder: 'PC / Console / Ultimate'
  },
  {
    id: 'icloud',
    name: 'iCloud+',
    brandTag: 'iC',
    category: 'software',
    itemType: 'subscription',
    defaultPrice: 2.99,
    defaultCurrency: 'EUR',
    billingCycle: 'monthly',
    remindDaysBefore: 3,
    color: '#0EA5E9',
    icon: '☁️',
    cancelUrl: 'https://support.apple.com/108047',
    notesPlaceholder: '50GB / 200GB / 2TB',
    plans: [
      { label: '50 GB (0,99 €)', price: 0.99, currency: 'EUR', cycle: 'monthly' },
      { label: '200 GB (2,99 €)', price: 2.99, currency: 'EUR', cycle: 'monthly' },
      { label: '2 TB (9,99 €)', price: 9.99, currency: 'EUR', cycle: 'monthly' }
    ]
  },
  {
    id: 'google-one',
    name: 'Google One',
    brandTag: 'G1',
    category: 'software',
    itemType: 'subscription',
    defaultPrice: 1.99,
    defaultCurrency: 'EUR',
    billingCycle: 'monthly',
    remindDaysBefore: 3,
    color: '#4285F4',
    icon: '🌈',
    cancelUrl: 'https://one.google.com/settings',
    notesPlaceholder: '100GB / 2TB / AI Premium'
  },

  // --- BOLLETTE & UTENZE ITALIA 🇮🇹 ---
  {
    id: 'bolletta-luce',
    name: 'Bolletta Luce 🇮🇹',
    brandTag: 'LUCE',
    category: 'bills',
    itemType: 'bill',
    defaultPrice: 85.00,
    defaultCurrency: 'EUR',
    billingCycle: 'bimonthly',
    remindDaysBefore: 7,
    color: '#F59E0B',
    icon: '⚡',
    cancelUrl: '',
    notesPlaceholder: 'Enel, Plenitude, A2A, Edison, Sorgenia...'
  },
  {
    id: 'bolletta-gas',
    name: 'Bolletta Gas 🇮🇹',
    brandTag: 'GAS',
    category: 'bills',
    itemType: 'bill',
    defaultPrice: 95.00,
    defaultCurrency: 'EUR',
    billingCycle: 'bimonthly',
    remindDaysBefore: 7,
    color: '#EF4444',
    icon: '🔥',
    cancelUrl: '',
    notesPlaceholder: 'Fornitore Gas / Lettura contatore'
  },
  {
    id: 'fibra-casa',
    name: 'Internet Fibra Casa 🇮🇹',
    brandTag: 'WIFI',
    category: 'bills',
    itemType: 'bill',
    defaultPrice: 27.90,
    defaultCurrency: 'EUR',
    billingCycle: 'monthly',
    remindDaysBefore: 5,
    color: '#6366F1',
    icon: '🌐',
    cancelUrl: '',
    notesPlaceholder: 'TIM / Vodafone / Fastweb / Iliad / WindTre'
  },
  {
    id: 'tari',
    name: 'TARI (Tassa Rifiuti) 🇮🇹',
    brandTag: 'TARI',
    category: 'bills',
    itemType: 'bill',
    defaultPrice: 180.00,
    defaultCurrency: 'EUR',
    billingCycle: 'yearly',
    remindDaysBefore: 14,
    color: '#10B981',
    icon: '♻️',
    cancelUrl: '',
    notesPlaceholder: 'Rata TARI Comunale / PagoPA'
  },

  // --- FACTURI & UTILITĂȚI ROMANIA 🇷🇴 ---
  {
    id: 'digi-ro',
    name: 'DIGI (RCS & RDS) 🇷🇴',
    brandTag: 'DIGI',
    category: 'bills',
    itemType: 'bill',
    defaultPrice: 95.00,
    defaultCurrency: 'RON',
    billingCycle: 'monthly',
    remindDaysBefore: 5,
    color: '#0284C7',
    icon: '🌐',
    cancelUrl: 'https://www.digi.ro/my-digi',
    notesPlaceholder: 'Internet Fibra + TV + Mobil (Contul Meu DIGI)'
  },
  {
    id: 'curent-ro',
    name: 'Curent Electric (PPC / Hidroelectrica) 🇷🇴',
    brandTag: 'PPC',
    category: 'bills',
    itemType: 'bill',
    defaultPrice: 180.00,
    defaultCurrency: 'RON',
    billingCycle: 'monthly',
    remindDaysBefore: 7,
    color: '#F59E0B',
    icon: '⚡',
    cancelUrl: '',
    notesPlaceholder: 'Factură energie electrică + transmitere index'
  },
  {
    id: 'gaze-ro',
    name: 'Gaze Naturale (Engie / E.ON) 🇷🇴',
    brandTag: 'GAZ',
    category: 'bills',
    itemType: 'bill',
    defaultPrice: 220.00,
    defaultCurrency: 'RON',
    billingCycle: 'monthly',
    remindDaysBefore: 7,
    color: '#EF4444',
    icon: '🔥',
    cancelUrl: '',
    notesPlaceholder: 'Factură gaze + autocitire index'
  },
  {
    id: 'intretinere-ro',
    name: 'Întreținere Bloc (e-Bloc / Pago) 🇷🇴',
    brandTag: 'BLOC',
    category: 'bills',
    itemType: 'bill',
    defaultPrice: 350.00,
    defaultCurrency: 'RON',
    billingCycle: 'monthly',
    remindDaysBefore: 7,
    color: '#64748B',
    icon: '🏢',
    cancelUrl: 'https://www.e-bloc.ro/',
    notesPlaceholder: 'Asociația de proprietari / Apă rece & caldă'
  },
  {
    id: 'mobil-ro',
    name: 'Orange / Vodafone / YOXO 🇷🇴',
    brandTag: 'SIM',
    category: 'bills',
    itemType: 'subscription',
    defaultPrice: 39.00,
    defaultCurrency: 'RON',
    billingCycle: 'monthly',
    remindDaysBefore: 3,
    color: '#F97316',
    icon: '📱',
    cancelUrl: '',
    notesPlaceholder: 'Abonament telefon mobil Romania'
  },

  // --- AUTO & VEICOLI (ITALIA 🇮🇹 + ROMANIA 🇷🇴) ---
  {
    id: 'bollo-auto',
    name: 'Bollo Auto 🇮🇹',
    brandTag: 'ACI',
    category: 'auto',
    itemType: 'bill',
    defaultPrice: 210.00,
    defaultCurrency: 'EUR',
    billingCycle: 'yearly',
    remindDaysBefore: 15,
    color: '#DC2626',
    icon: '🚗',
    cancelUrl: 'https://www.aci.it/i-servizi/servizi-online/bollo-auto.html',
    notesPlaceholder: 'Inserisci Targa veicolo e Regione'
  },
  {
    id: 'assicurazione-auto',
    name: 'Assicurazione Auto (RCA) 🇮🇹',
    brandTag: 'RCA',
    category: 'auto',
    itemType: 'bill',
    defaultPrice: 480.00,
    defaultCurrency: 'EUR',
    billingCycle: 'yearly',
    remindDaysBefore: 15,
    color: '#2563EB',
    icon: '🛡️',
    cancelUrl: '',
    notesPlaceholder: 'Compagnia assicurativa + Targa'
  },
  {
    id: 'rovinieta-ro',
    name: 'Rovinietă Auto (CNAIR) 🇷🇴',
    brandTag: 'ROV',
    category: 'auto',
    itemType: 'bill',
    defaultPrice: 139.00,
    defaultCurrency: 'RON',
    billingCycle: 'yearly',
    remindDaysBefore: 10,
    color: '#DC2626',
    icon: '🛣️',
    cancelUrl: 'https://www.erovinieta.ro/',
    notesPlaceholder: 'Număr înmatriculare • Rovinietă 12 luni / 30 zile'
  },
  {
    id: 'rca-ro',
    name: 'Asigurare RCA Auto 🇷🇴',
    brandTag: 'RCA',
    category: 'auto',
    itemType: 'bill',
    defaultPrice: 950.00,
    defaultCurrency: 'RON',
    billingCycle: 'yearly',
    remindDaysBefore: 15,
    color: '#2563EB',
    icon: '🛡️',
    cancelUrl: '',
    notesPlaceholder: 'Poliță RCA obligatorie + Număr auto'
  },
  {
    id: 'impozit-auto-ro',
    name: 'Impozit Auto (Ghișeul.ro) 🇷🇴',
    brandTag: 'TAX',
    category: 'auto',
    itemType: 'bill',
    defaultPrice: 200.00,
    defaultCurrency: 'RON',
    billingCycle: 'yearly',
    remindDaysBefore: 15,
    color: '#059669',
    icon: '🏛️',
    cancelUrl: 'https://www.ghiseul.ro/',
    notesPlaceholder: 'Impozit anual cu reducere până la 31 Martie'
  },
  {
    id: 'itp-ro',
    name: 'ITP Auto (RAR) 🇷🇴',
    brandTag: 'ITP',
    category: 'auto',
    itemType: 'bill',
    defaultPrice: 180.00,
    defaultCurrency: 'RON',
    billingCycle: 'Biennial',
    remindDaysBefore: 20,
    color: '#D97706',
    icon: '🔧',
    cancelUrl: 'https://www.rarom.ro/',
    notesPlaceholder: 'Expirare ITP RAR'
  },

  // --- CASA, SALUTE & ALTRO ---
  {
    id: 'palestra',
    name: 'Palestra / Sală Fitness',
    brandTag: 'GYM',
    category: 'other',
    itemType: 'subscription',
    defaultPrice: 45.00,
    defaultCurrency: 'EUR',
    billingCycle: 'monthly',
    remindDaysBefore: 7,
    color: '#EC4899',
    icon: '🏋️',
    cancelUrl: '',
    notesPlaceholder: 'Palestra / 7card / ESX / World Class'
  },
  {
    id: 'affitto-mutuo',
    name: 'Affitto / Mutuo / Chirie',
    brandTag: 'HOME',
    category: 'other',
    itemType: 'bill',
    defaultPrice: 600.00,
    defaultCurrency: 'EUR',
    billingCycle: 'monthly',
    remindDaysBefore: 5,
    color: '#4F46E5',
    icon: '🏠',
    cancelUrl: '',
    notesPlaceholder: 'Bonifico mensile / Addebito rata'
  }
];

window.CATEGORY_META = {
  streaming: { label: 'Streaming & Media', label_ro: 'Streaming & Media', icon: '🎬', badgeColor: '#E50914' },
  software: { label: 'App, Gaming & Cloud', label_ro: 'App, Gaming & Cloud', icon: '💻', badgeColor: '#10A37F' },
  bills: { label: 'Bollette & Utenze', label_ro: 'Facturi & Utilități', icon: '⚡', badgeColor: '#F59E0B' },
  auto: { label: 'Bollo Auto & Veicoli', label_ro: 'Auto, Rovinietă & RCA', icon: '🚗', badgeColor: '#DC2626' },
  other: { label: 'Casa, Tasse & Altro', label_ro: 'Casă, Taxe & Altele', icon: '🏠', badgeColor: '#8B5CF6' }
};

window.BILLING_CYCLES = {
  monthly: { label: 'Mensile', label_ro: 'Lunar', months: 1, short: '/mese', short_ro: '/lună' },
  bimonthly: { label: 'Bimestrale (ogni 2 mesi)', label_ro: 'Bilunar (la 2 luni)', months: 2, short: '/2 mesi', short_ro: '/2 luni' },
  quarterly: { label: 'Trimestrale (ogni 3 mesi)', label_ro: 'Trimestrial (la 3 luni)', months: 3, short: '/3 mesi', short_ro: '/3 luni' },
  semiannual: { label: 'Semestrale (ogni 6 mesi)', label_ro: 'Semestrial (la 6 luni)', months: 6, short: '/6 mesi', short_ro: '/6 luni' },
  yearly: { label: 'Annuale (ogni anno)', label_ro: 'Anual (în fiecare an)', months: 12, short: '/anno', short_ro: '/an' },
  Biennial: { label: 'Biennale (ogni 2 anni)', label_ro: 'La 2 ani (Bienal)', months: 24, short: '/2 anni', short_ro: '/2 ani' },
  once: { label: 'Singola Scadenza (1 solo mese)', label_ro: 'O singură dată (1 lună)', months: 0, short: '1 mese', short_ro: 'o dată' }
};
