// Catalogo predefinito di Abbonamenti, Bollette, Bollo Auto e Scadenze Ricorrenti
window.SERVICE_PRESETS = [
  // --- STREAMING & INTRATTENIMENTO ---
  {
    id: 'netflix',
    name: 'Netflix',
    category: 'streaming',
    itemType: 'subscription', // 'subscription' (rinnovo automatico / disdicibile) | 'bill' (da pagare)
    defaultPrice: 13.99,
    billingCycle: 'monthly',
    remindDaysBefore: 3,
    color: '#E50914',
    icon: '🎬',
    cancelUrl: 'https://www.netflix.com/youraccount',
    notesPlaceholder: 'Piano Standard / Premium'
  },
  {
    id: 'disneyplus',
    name: 'Disney+',
    category: 'streaming',
    itemType: 'subscription',
    defaultPrice: 9.99,
    billingCycle: 'monthly',
    remindDaysBefore: 3,
    color: '#0063E5',
    icon: '✨',
    cancelUrl: 'https://www.disneyplus.com/it-it/account/subscription',
    notesPlaceholder: 'Piano Standard con o senza pubblicità'
  },
  {
    id: 'amazon-prime',
    name: 'Amazon Prime',
    category: 'streaming',
    itemType: 'subscription',
    defaultPrice: 4.99,
    billingCycle: 'monthly',
    remindDaysBefore: 5,
    color: '#00A8E1',
    icon: '📦',
    cancelUrl: 'https://www.amazon.it/mc',
    notesPlaceholder: 'Prime Video + Spedizioni'
  },
  {
    id: 'spotify',
    name: 'Spotify Premium',
    category: 'streaming',
    itemType: 'subscription',
    defaultPrice: 10.99,
    billingCycle: 'monthly',
    remindDaysBefore: 3,
    color: '#1DB954',
    icon: '🎧',
    cancelUrl: 'https://www.spotify.com/it/account/subscription/',
    notesPlaceholder: 'Individual / Duo / Family'
  },
  {
    id: 'dazn',
    name: 'DAZN',
    category: 'streaming',
    itemType: 'subscription',
    defaultPrice: 34.99,
    billingCycle: 'monthly',
    remindDaysBefore: 7,
    color: '#1E1E1E',
    icon: '⚽',
    cancelUrl: 'https://www.dazn.com/it-IT/myaccount',
    notesPlaceholder: 'Attenzione al preavviso di disdetta!'
  },
  {
    id: 'nowtv',
    name: 'NOW TV',
    category: 'streaming',
    itemType: 'subscription',
    defaultPrice: 14.99,
    billingCycle: 'monthly',
    remindDaysBefore: 3,
    color: '#00D66C',
    icon: '📺',
    cancelUrl: 'https://www.nowtv.it/area-personale',
    notesPlaceholder: 'Pass Cinema / Entertainment / Sport'
  },
  {
    id: 'youtube-premium',
    name: 'YouTube Premium',
    category: 'streaming',
    itemType: 'subscription',
    defaultPrice: 11.99,
    billingCycle: 'monthly',
    remindDaysBefore: 3,
    color: '#FF0000',
    icon: '▶️',
    cancelUrl: 'https://www.youtube.com/paid_memberships',
    notesPlaceholder: 'YouTube senza pubblicità + Music'
  },
  {
    id: 'apple-tv',
    name: 'Apple TV+',
    category: 'streaming',
    itemType: 'subscription',
    defaultPrice: 9.99,
    billingCycle: 'monthly',
    remindDaysBefore: 3,
    color: '#334155',
    icon: '🍎',
    cancelUrl: 'https://support.apple.com/it-it/HT202039',
    notesPlaceholder: 'Gestibile da Impostazioni ID Apple'
  },
  {
    id: 'paramount',
    name: 'Paramount+',
    category: 'streaming',
    itemType: 'subscription',
    defaultPrice: 7.99,
    billingCycle: 'monthly',
    remindDaysBefore: 3,
    color: '#0064FF',
    icon: '🏔️',
    cancelUrl: 'https://www.paramountplus.com/account/',
    notesPlaceholder: 'Abbonamento mensile'
  },
  {
    id: 'crunchyroll',
    name: 'Crunchyroll',
    category: 'streaming',
    itemType: 'subscription',
    defaultPrice: 4.99,
    billingCycle: 'monthly',
    remindDaysBefore: 3,
    color: '#F47521',
    icon: '🍥',
    cancelUrl: 'https://www.crunchyroll.com/acct/membership',
    notesPlaceholder: 'Fan / Mega Fan'
  },
  {
    id: 'audible',
    name: 'Audible',
    category: 'streaming',
    itemType: 'subscription',
    defaultPrice: 9.99,
    billingCycle: 'monthly',
    remindDaysBefore: 3,
    color: '#F8991D',
    icon: '📖',
    cancelUrl: 'https://www.audible.it/account/overview',
    notesPlaceholder: 'Audiolibri mensili'
  },

  // --- GAMING, SOFTWARE & AI ---
  {
    id: 'chatgpt',
    name: 'ChatGPT Plus',
    category: 'software',
    itemType: 'subscription',
    defaultPrice: 22.00,
    billingCycle: 'monthly',
    remindDaysBefore: 3,
    color: '#10A37F',
    icon: '🤖',
    cancelUrl: 'https://chatgpt.com/#settings/Subscription',
    notesPlaceholder: 'OpenAI Plus'
  },
  {
    id: 'xbox-gamepass',
    name: 'Xbox Game Pass',
    category: 'software',
    itemType: 'subscription',
    defaultPrice: 14.99,
    billingCycle: 'monthly',
    remindDaysBefore: 3,
    color: '#107C10',
    icon: '🎮',
    cancelUrl: 'https://account.microsoft.com/services',
    notesPlaceholder: 'PC / Console / Ultimate'
  },
  {
    id: 'ps-plus',
    name: 'PlayStation Plus',
    category: 'software',
    itemType: 'subscription',
    defaultPrice: 8.99,
    billingCycle: 'monthly',
    remindDaysBefore: 3,
    color: '#00439C',
    icon: '🕹️',
    cancelUrl: 'https://store.playstation.com/',
    notesPlaceholder: 'Essential / Extra / Premium'
  },
  {
    id: 'icloud',
    name: 'iCloud+',
    category: 'software',
    itemType: 'subscription',
    defaultPrice: 2.99,
    billingCycle: 'monthly',
    remindDaysBefore: 3,
    color: '#0EA5E9',
    icon: '☁️',
    cancelUrl: 'https://support.apple.com/it-it/108047',
    notesPlaceholder: '50GB / 200GB / 2TB'
  },
  {
    id: 'google-one',
    name: 'Google One',
    category: 'software',
    itemType: 'subscription',
    defaultPrice: 1.99,
    billingCycle: 'monthly',
    remindDaysBefore: 3,
    color: '#4285F4',
    icon: '🌈',
    cancelUrl: 'https://one.google.com/settings',
    notesPlaceholder: 'Spazio archiviazione Google'
  },
  {
    id: 'adobe',
    name: 'Adobe Creative Cloud',
    category: 'software',
    itemType: 'subscription',
    defaultPrice: 24.39,
    billingCycle: 'monthly',
    remindDaysBefore: 7,
    color: '#FF0000',
    icon: '🎨',
    cancelUrl: 'https://account.adobe.com/plans',
    notesPlaceholder: 'Attenzione a eventuali penali annuali'
  },
  {
    id: 'nordvpn',
    name: 'NordVPN / VPN',
    category: 'software',
    itemType: 'subscription',
    defaultPrice: 12.99,
    billingCycle: 'monthly',
    remindDaysBefore: 5,
    color: '#4687FF',
    icon: '🛡️',
    cancelUrl: 'https://my.nordaccount.com/',
    notesPlaceholder: 'Servizio VPN'
  },

  // --- BOLLETTE & UTENZE ---
  {
    id: 'bolletta-luce',
    name: 'Bolletta Luce (Elettricità)',
    category: 'bills',
    itemType: 'bill',
    defaultPrice: 85.00,
    billingCycle: 'bimonthly',
    remindDaysBefore: 7,
    color: '#F59E0B',
    icon: '⚡',
    cancelUrl: '',
    notesPlaceholder: 'Fornitore (es. Enel, Plenitude, A2A, Edison...)'
  },
  {
    id: 'bolletta-gas',
    name: 'Bolletta Gas',
    category: 'bills',
    itemType: 'bill',
    defaultPrice: 95.00,
    billingCycle: 'bimonthly',
    remindDaysBefore: 7,
    color: '#EF4444',
    icon: '🔥',
    cancelUrl: '',
    notesPlaceholder: 'Fornitore Gas / Lettura contatore'
  },
  {
    id: 'bolletta-acqua',
    name: 'Bolletta Acqua',
    category: 'bills',
    itemType: 'bill',
    defaultPrice: 45.00,
    billingCycle: 'quarterly',
    remindDaysBefore: 7,
    color: '#06B6D4',
    icon: '💧',
    cancelUrl: '',
    notesPlaceholder: 'Gestore idrico locale'
  },
  {
    id: 'fibra-casa',
    name: 'Internet Fibra / Casa',
    category: 'bills',
    itemType: 'bill',
    defaultPrice: 27.90,
    billingCycle: 'monthly',
    remindDaysBefore: 5,
    color: '#6366F1',
    icon: '🌐',
    cancelUrl: '',
    notesPlaceholder: 'TIM / Vodafone / Fastweb / Iliad / WindTre'
  },
  {
    id: 'sim-mobile',
    name: 'Offerta SIM Mobile',
    category: 'bills',
    itemType: 'subscription',
    defaultPrice: 9.99,
    billingCycle: 'monthly',
    remindDaysBefore: 2,
    color: '#8B5CF6',
    icon: '📱',
    cancelUrl: '',
    notesPlaceholder: 'Ricarica per rinnovo offerta mensile'
  },
  {
    id: 'tari',
    name: 'TARI (Tassa Rifiuti)',
    category: 'bills',
    itemType: 'bill',
    defaultPrice: 180.00,
    billingCycle: 'yearly',
    remindDaysBefore: 14,
    color: '#10B981',
    icon: '♻️',
    cancelUrl: '',
    notesPlaceholder: 'Rata TARI Comunale / PagoPA'
  },
  {
    id: 'condominio',
    name: 'Spese Condominiali',
    category: 'bills',
    itemType: 'bill',
    defaultPrice: 100.00,
    billingCycle: 'monthly',
    remindDaysBefore: 7,
    color: '#64748B',
    icon: '🏢',
    cancelUrl: '',
    notesPlaceholder: 'Rata ordinaria / straordinaria condominio'
  },

  // --- AUTO & VEICOLI ---
  {
    id: 'bollo-auto',
    name: 'Bollo Auto',
    category: 'auto',
    itemType: 'bill',
    defaultPrice: 210.00,
    billingCycle: 'yearly',
    remindDaysBefore: 15,
    color: '#DC2626',
    icon: '🚗',
    cancelUrl: 'https://www.aci.it/i-servizi/servizi-online/bollo-auto.html',
    notesPlaceholder: 'Inserisci Targa veicolo e Regione'
  },
  {
    id: 'assicurazione-auto',
    name: 'Assicurazione Auto (RCA)',
    category: 'auto',
    itemType: 'bill',
    defaultPrice: 480.00,
    billingCycle: 'yearly',
    remindDaysBefore: 15,
    color: '#2563EB',
    icon: '🛡️',
    cancelUrl: '',
    notesPlaceholder: 'Compagnia assicurativa + Targa'
  },
  {
    id: 'revisione-auto',
    name: 'Revisione Auto',
    category: 'auto',
    itemType: 'bill',
    defaultPrice: 79.00,
    billingCycle: 'Biennial',
    remindDaysBefore: 20,
    color: '#D97706',
    icon: '🔧',
    cancelUrl: 'https://www.ilportaledellautomobilista.it/',
    notesPlaceholder: 'Scadenza revisione ministeriale (ogni 2 anni)'
  },
  {
    id: 'telepass',
    name: 'Telepass / UnipolMove',
    category: 'auto',
    itemType: 'subscription',
    defaultPrice: 3.90,
    billingCycle: 'monthly',
    remindDaysBefore: 5,
    color: '#FACC15',
    icon: '🛣️',
    cancelUrl: '',
    notesPlaceholder: 'Canone + addebito pedaggi'
  },

  // --- CASA, SALUTE & ALTRO ---
  {
    id: 'palestra',
    name: 'Abbonamento Palestra',
    category: 'other',
    itemType: 'subscription',
    defaultPrice: 45.00,
    billingCycle: 'monthly',
    remindDaysBefore: 7,
    color: '#EC4899',
    icon: '🏋️',
    cancelUrl: '',
    notesPlaceholder: 'Mensile / Annuale + scadenza certificato medico'
  },
  {
    id: 'affitto-mutuo',
    name: 'Affitto / Rata Mutuo',
    category: 'other',
    itemType: 'bill',
    defaultPrice: 650.00,
    billingCycle: 'monthly',
    remindDaysBefore: 5,
    color: '#4F46E5',
    icon: '🏠',
    cancelUrl: '',
    notesPlaceholder: 'Bonifico mensile / Addebito rata'
  }
];

window.CATEGORY_META = {
  streaming: { label: 'Streaming & Media', icon: '🎬', badgeColor: '#E50914' },
  software: { label: 'App, Gaming & Cloud', icon: '💻', badgeColor: '#10A37F' },
  bills: { label: 'Bollette & Utenze', icon: '⚡', badgeColor: '#F59E0B' },
  auto: { label: 'Bollo Auto & Veicoli', icon: '🚗', badgeColor: '#DC2626' },
  other: { label: 'Casa, Tasse & Altro', icon: '🏠', badgeColor: '#8B5CF6' }
};

window.BILLING_CYCLES = {
  monthly: { label: 'Mensile', months: 1, short: '/mese' },
  bimonthly: { label: 'Bimestrale (ogni 2 mesi)', months: 2, short: '/2 mesi' },
  quarterly: { label: 'Trimestrale (ogni 3 mesi)', months: 3, short: '/3 mesi' },
  semiannual: { label: 'Semestrale (ogni 6 mesi)', months: 6, short: '/6 mesi' },
  yearly: { label: 'Annuale (ogni anno)', months: 12, short: '/anno' },
  Biennial: { label: 'Biennale (ogni 2 anni)', months: 24, short: '/2 anni' },
  once: { label: 'Singola Scadenza (1 solo mese / Una tantum)', months: 0, short: 'una tantum' }
};
